//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasseMetier.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.BasicServicePortType")]
    public interface BasicServicePortType {
        
        // CODEGEN : La génération du contrat de message depuis l'opération SetBinaryState n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#SetBinaryState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClasseMetier.ServiceReference1.SetBinaryStateResponse1 SetBinaryState(ClasseMetier.ServiceReference1.SetBinaryStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#SetBinaryState", ReplyAction="*")]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.SetBinaryStateResponse1> SetBinaryStateAsync(ClasseMetier.ServiceReference1.SetBinaryStateRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GetBinaryState n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetBinaryState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClasseMetier.ServiceReference1.GetBinaryStateResponse1 GetBinaryState(ClasseMetier.ServiceReference1.GetBinaryStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetBinaryState", ReplyAction="*")]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetBinaryStateResponse1> GetBinaryStateAsync(ClasseMetier.ServiceReference1.GetBinaryStateRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GetFriendlyName n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetFriendlyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClasseMetier.ServiceReference1.GetFriendlyNameResponse1 GetFriendlyName(ClasseMetier.ServiceReference1.GetFriendlyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetFriendlyName", ReplyAction="*")]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetFriendlyNameResponse1> GetFriendlyNameAsync(ClasseMetier.ServiceReference1.GetFriendlyNameRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GetHomeId n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetHomeId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClasseMetier.ServiceReference1.GetHomeIdResponse1 GetHomeId(ClasseMetier.ServiceReference1.GetHomeIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetHomeId", ReplyAction="*")]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetHomeIdResponse1> GetHomeIdAsync(ClasseMetier.ServiceReference1.GetHomeIdRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GetSignalStrength n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetSignalStrength", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClasseMetier.ServiceReference1.GetSignalStrengthResponse1 GetSignalStrength(ClasseMetier.ServiceReference1.GetSignalStrengthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetSignalStrength", ReplyAction="*")]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetSignalStrengthResponse1> GetSignalStrengthAsync(ClasseMetier.ServiceReference1.GetSignalStrengthRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GetLogFileURL n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetLogFileURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClasseMetier.ServiceReference1.GetLogFileURLResponse1 GetLogFileURL(ClasseMetier.ServiceReference1.GetLogFileURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetLogFileURL", ReplyAction="*")]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetLogFileURLResponse1> GetLogFileURLAsync(ClasseMetier.ServiceReference1.GetLogFileURLRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GetIconURL n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetIconURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClasseMetier.ServiceReference1.GetIconURLResponse1 GetIconURL(ClasseMetier.ServiceReference1.GetIconURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetIconURL", ReplyAction="*")]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetIconURLResponse1> GetIconURLAsync(ClasseMetier.ServiceReference1.GetIconURLRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération ChangeFriendlyName n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#ChangeFriendlyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClasseMetier.ServiceReference1.ChangeFriendlyNameResponse1 ChangeFriendlyName(ClasseMetier.ServiceReference1.ChangeFriendlyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#ChangeFriendlyName", ReplyAction="*")]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.ChangeFriendlyNameResponse1> ChangeFriendlyNameAsync(ClasseMetier.ServiceReference1.ChangeFriendlyNameRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class SetBinaryState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binaryStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BinaryState {
            get {
                return this.binaryStateField;
            }
            set {
                this.binaryStateField = value;
                this.RaisePropertyChanged("BinaryState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class SetBinaryStateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binaryStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BinaryState {
            get {
                return this.binaryStateField;
            }
            set {
                this.binaryStateField = value;
                this.RaisePropertyChanged("BinaryState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBinaryStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.SetBinaryState SetBinaryState;
        
        public SetBinaryStateRequest() {
        }
        
        public SetBinaryStateRequest(ClasseMetier.ServiceReference1.SetBinaryState SetBinaryState) {
            this.SetBinaryState = SetBinaryState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBinaryStateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.SetBinaryStateResponse SetBinaryStateResponse;
        
        public SetBinaryStateResponse1() {
        }
        
        public SetBinaryStateResponse1(ClasseMetier.ServiceReference1.SetBinaryStateResponse SetBinaryStateResponse) {
            this.SetBinaryStateResponse = SetBinaryStateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetBinaryState : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetBinaryStateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binaryStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BinaryState {
            get {
                return this.binaryStateField;
            }
            set {
                this.binaryStateField = value;
                this.RaisePropertyChanged("BinaryState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBinaryStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetBinaryState GetBinaryState;
        
        public GetBinaryStateRequest() {
        }
        
        public GetBinaryStateRequest(ClasseMetier.ServiceReference1.GetBinaryState GetBinaryState) {
            this.GetBinaryState = GetBinaryState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBinaryStateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetBinaryStateResponse GetBinaryStateResponse;
        
        public GetBinaryStateResponse1() {
        }
        
        public GetBinaryStateResponse1(ClasseMetier.ServiceReference1.GetBinaryStateResponse GetBinaryStateResponse) {
            this.GetBinaryStateResponse = GetBinaryStateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetFriendlyName : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetFriendlyNameResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string friendlyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FriendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
                this.RaisePropertyChanged("FriendlyName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFriendlyNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetFriendlyName GetFriendlyName;
        
        public GetFriendlyNameRequest() {
        }
        
        public GetFriendlyNameRequest(ClasseMetier.ServiceReference1.GetFriendlyName GetFriendlyName) {
            this.GetFriendlyName = GetFriendlyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFriendlyNameResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetFriendlyNameResponse GetFriendlyNameResponse;
        
        public GetFriendlyNameResponse1() {
        }
        
        public GetFriendlyNameResponse1(ClasseMetier.ServiceReference1.GetFriendlyNameResponse GetFriendlyNameResponse) {
            this.GetFriendlyNameResponse = GetFriendlyNameResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetHomeId : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetHomeIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string homeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HomeId {
            get {
                return this.homeIdField;
            }
            set {
                this.homeIdField = value;
                this.RaisePropertyChanged("HomeId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHomeIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetHomeId GetHomeId;
        
        public GetHomeIdRequest() {
        }
        
        public GetHomeIdRequest(ClasseMetier.ServiceReference1.GetHomeId GetHomeId) {
            this.GetHomeId = GetHomeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHomeIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetHomeIdResponse GetHomeIdResponse;
        
        public GetHomeIdResponse1() {
        }
        
        public GetHomeIdResponse1(ClasseMetier.ServiceReference1.GetHomeIdResponse GetHomeIdResponse) {
            this.GetHomeIdResponse = GetHomeIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetSignalStrength : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetSignalStrengthResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signalStrengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SignalStrength {
            get {
                return this.signalStrengthField;
            }
            set {
                this.signalStrengthField = value;
                this.RaisePropertyChanged("SignalStrength");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignalStrengthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetSignalStrength GetSignalStrength;
        
        public GetSignalStrengthRequest() {
        }
        
        public GetSignalStrengthRequest(ClasseMetier.ServiceReference1.GetSignalStrength GetSignalStrength) {
            this.GetSignalStrength = GetSignalStrength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignalStrengthResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetSignalStrengthResponse GetSignalStrengthResponse;
        
        public GetSignalStrengthResponse1() {
        }
        
        public GetSignalStrengthResponse1(ClasseMetier.ServiceReference1.GetSignalStrengthResponse GetSignalStrengthResponse) {
            this.GetSignalStrengthResponse = GetSignalStrengthResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetLogFileURL : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetLogFileURLResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lOGURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOGURL {
            get {
                return this.lOGURLField;
            }
            set {
                this.lOGURLField = value;
                this.RaisePropertyChanged("LOGURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogFileURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetLogFileURL GetLogFileURL;
        
        public GetLogFileURLRequest() {
        }
        
        public GetLogFileURLRequest(ClasseMetier.ServiceReference1.GetLogFileURL GetLogFileURL) {
            this.GetLogFileURL = GetLogFileURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogFileURLResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetLogFileURLResponse GetLogFileURLResponse;
        
        public GetLogFileURLResponse1() {
        }
        
        public GetLogFileURLResponse1(ClasseMetier.ServiceReference1.GetLogFileURLResponse GetLogFileURLResponse) {
            this.GetLogFileURLResponse = GetLogFileURLResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetIconURL : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetIconURLResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uRLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIconURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetIconURL GetIconURL;
        
        public GetIconURLRequest() {
        }
        
        public GetIconURLRequest(ClasseMetier.ServiceReference1.GetIconURL GetIconURL) {
            this.GetIconURL = GetIconURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIconURLResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.GetIconURLResponse GetIconURLResponse;
        
        public GetIconURLResponse1() {
        }
        
        public GetIconURLResponse1(ClasseMetier.ServiceReference1.GetIconURLResponse GetIconURLResponse) {
            this.GetIconURLResponse = GetIconURLResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class ChangeFriendlyName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string friendlyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FriendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
                this.RaisePropertyChanged("FriendlyName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class ChangeFriendlyNameResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeFriendlyNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.ChangeFriendlyName ChangeFriendlyName;
        
        public ChangeFriendlyNameRequest() {
        }
        
        public ChangeFriendlyNameRequest(ClasseMetier.ServiceReference1.ChangeFriendlyName ChangeFriendlyName) {
            this.ChangeFriendlyName = ChangeFriendlyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeFriendlyNameResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public ClasseMetier.ServiceReference1.ChangeFriendlyNameResponse ChangeFriendlyNameResponse;
        
        public ChangeFriendlyNameResponse1() {
        }
        
        public ChangeFriendlyNameResponse1(ClasseMetier.ServiceReference1.ChangeFriendlyNameResponse ChangeFriendlyNameResponse) {
            this.ChangeFriendlyNameResponse = ChangeFriendlyNameResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BasicServicePortTypeChannel : ClasseMetier.ServiceReference1.BasicServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasicServicePortTypeClient : System.ServiceModel.ClientBase<ClasseMetier.ServiceReference1.BasicServicePortType>, ClasseMetier.ServiceReference1.BasicServicePortType {
        
        public BasicServicePortTypeClient() {
        }
        
        public BasicServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClasseMetier.ServiceReference1.SetBinaryStateResponse1 ClasseMetier.ServiceReference1.BasicServicePortType.SetBinaryState(ClasseMetier.ServiceReference1.SetBinaryStateRequest request) {
            return base.Channel.SetBinaryState(request);
        }
        
        public ClasseMetier.ServiceReference1.SetBinaryStateResponse SetBinaryState(ClasseMetier.ServiceReference1.SetBinaryState SetBinaryState1) {
            ClasseMetier.ServiceReference1.SetBinaryStateRequest inValue = new ClasseMetier.ServiceReference1.SetBinaryStateRequest();
            inValue.SetBinaryState = SetBinaryState1;
            ClasseMetier.ServiceReference1.SetBinaryStateResponse1 retVal = ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).SetBinaryState(inValue);
            return retVal.SetBinaryStateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.SetBinaryStateResponse1> ClasseMetier.ServiceReference1.BasicServicePortType.SetBinaryStateAsync(ClasseMetier.ServiceReference1.SetBinaryStateRequest request) {
            return base.Channel.SetBinaryStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.SetBinaryStateResponse1> SetBinaryStateAsync(ClasseMetier.ServiceReference1.SetBinaryState SetBinaryState) {
            ClasseMetier.ServiceReference1.SetBinaryStateRequest inValue = new ClasseMetier.ServiceReference1.SetBinaryStateRequest();
            inValue.SetBinaryState = SetBinaryState;
            return ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).SetBinaryStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClasseMetier.ServiceReference1.GetBinaryStateResponse1 ClasseMetier.ServiceReference1.BasicServicePortType.GetBinaryState(ClasseMetier.ServiceReference1.GetBinaryStateRequest request) {
            return base.Channel.GetBinaryState(request);
        }
        
        public ClasseMetier.ServiceReference1.GetBinaryStateResponse GetBinaryState(ClasseMetier.ServiceReference1.GetBinaryState GetBinaryState1) {
            ClasseMetier.ServiceReference1.GetBinaryStateRequest inValue = new ClasseMetier.ServiceReference1.GetBinaryStateRequest();
            inValue.GetBinaryState = GetBinaryState1;
            ClasseMetier.ServiceReference1.GetBinaryStateResponse1 retVal = ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetBinaryState(inValue);
            return retVal.GetBinaryStateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetBinaryStateResponse1> ClasseMetier.ServiceReference1.BasicServicePortType.GetBinaryStateAsync(ClasseMetier.ServiceReference1.GetBinaryStateRequest request) {
            return base.Channel.GetBinaryStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetBinaryStateResponse1> GetBinaryStateAsync(ClasseMetier.ServiceReference1.GetBinaryState GetBinaryState) {
            ClasseMetier.ServiceReference1.GetBinaryStateRequest inValue = new ClasseMetier.ServiceReference1.GetBinaryStateRequest();
            inValue.GetBinaryState = GetBinaryState;
            return ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetBinaryStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClasseMetier.ServiceReference1.GetFriendlyNameResponse1 ClasseMetier.ServiceReference1.BasicServicePortType.GetFriendlyName(ClasseMetier.ServiceReference1.GetFriendlyNameRequest request) {
            return base.Channel.GetFriendlyName(request);
        }
        
        public ClasseMetier.ServiceReference1.GetFriendlyNameResponse GetFriendlyName(ClasseMetier.ServiceReference1.GetFriendlyName GetFriendlyName1) {
            ClasseMetier.ServiceReference1.GetFriendlyNameRequest inValue = new ClasseMetier.ServiceReference1.GetFriendlyNameRequest();
            inValue.GetFriendlyName = GetFriendlyName1;
            ClasseMetier.ServiceReference1.GetFriendlyNameResponse1 retVal = ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetFriendlyName(inValue);
            return retVal.GetFriendlyNameResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetFriendlyNameResponse1> ClasseMetier.ServiceReference1.BasicServicePortType.GetFriendlyNameAsync(ClasseMetier.ServiceReference1.GetFriendlyNameRequest request) {
            return base.Channel.GetFriendlyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetFriendlyNameResponse1> GetFriendlyNameAsync(ClasseMetier.ServiceReference1.GetFriendlyName GetFriendlyName) {
            ClasseMetier.ServiceReference1.GetFriendlyNameRequest inValue = new ClasseMetier.ServiceReference1.GetFriendlyNameRequest();
            inValue.GetFriendlyName = GetFriendlyName;
            return ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetFriendlyNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClasseMetier.ServiceReference1.GetHomeIdResponse1 ClasseMetier.ServiceReference1.BasicServicePortType.GetHomeId(ClasseMetier.ServiceReference1.GetHomeIdRequest request) {
            return base.Channel.GetHomeId(request);
        }
        
        public ClasseMetier.ServiceReference1.GetHomeIdResponse GetHomeId(ClasseMetier.ServiceReference1.GetHomeId GetHomeId1) {
            ClasseMetier.ServiceReference1.GetHomeIdRequest inValue = new ClasseMetier.ServiceReference1.GetHomeIdRequest();
            inValue.GetHomeId = GetHomeId1;
            ClasseMetier.ServiceReference1.GetHomeIdResponse1 retVal = ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetHomeId(inValue);
            return retVal.GetHomeIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetHomeIdResponse1> ClasseMetier.ServiceReference1.BasicServicePortType.GetHomeIdAsync(ClasseMetier.ServiceReference1.GetHomeIdRequest request) {
            return base.Channel.GetHomeIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetHomeIdResponse1> GetHomeIdAsync(ClasseMetier.ServiceReference1.GetHomeId GetHomeId) {
            ClasseMetier.ServiceReference1.GetHomeIdRequest inValue = new ClasseMetier.ServiceReference1.GetHomeIdRequest();
            inValue.GetHomeId = GetHomeId;
            return ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetHomeIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClasseMetier.ServiceReference1.GetSignalStrengthResponse1 ClasseMetier.ServiceReference1.BasicServicePortType.GetSignalStrength(ClasseMetier.ServiceReference1.GetSignalStrengthRequest request) {
            return base.Channel.GetSignalStrength(request);
        }
        
        public ClasseMetier.ServiceReference1.GetSignalStrengthResponse GetSignalStrength(ClasseMetier.ServiceReference1.GetSignalStrength GetSignalStrength1) {
            ClasseMetier.ServiceReference1.GetSignalStrengthRequest inValue = new ClasseMetier.ServiceReference1.GetSignalStrengthRequest();
            inValue.GetSignalStrength = GetSignalStrength1;
            ClasseMetier.ServiceReference1.GetSignalStrengthResponse1 retVal = ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetSignalStrength(inValue);
            return retVal.GetSignalStrengthResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetSignalStrengthResponse1> ClasseMetier.ServiceReference1.BasicServicePortType.GetSignalStrengthAsync(ClasseMetier.ServiceReference1.GetSignalStrengthRequest request) {
            return base.Channel.GetSignalStrengthAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetSignalStrengthResponse1> GetSignalStrengthAsync(ClasseMetier.ServiceReference1.GetSignalStrength GetSignalStrength) {
            ClasseMetier.ServiceReference1.GetSignalStrengthRequest inValue = new ClasseMetier.ServiceReference1.GetSignalStrengthRequest();
            inValue.GetSignalStrength = GetSignalStrength;
            return ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetSignalStrengthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClasseMetier.ServiceReference1.GetLogFileURLResponse1 ClasseMetier.ServiceReference1.BasicServicePortType.GetLogFileURL(ClasseMetier.ServiceReference1.GetLogFileURLRequest request) {
            return base.Channel.GetLogFileURL(request);
        }
        
        public ClasseMetier.ServiceReference1.GetLogFileURLResponse GetLogFileURL(ClasseMetier.ServiceReference1.GetLogFileURL GetLogFileURL1) {
            ClasseMetier.ServiceReference1.GetLogFileURLRequest inValue = new ClasseMetier.ServiceReference1.GetLogFileURLRequest();
            inValue.GetLogFileURL = GetLogFileURL1;
            ClasseMetier.ServiceReference1.GetLogFileURLResponse1 retVal = ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetLogFileURL(inValue);
            return retVal.GetLogFileURLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetLogFileURLResponse1> ClasseMetier.ServiceReference1.BasicServicePortType.GetLogFileURLAsync(ClasseMetier.ServiceReference1.GetLogFileURLRequest request) {
            return base.Channel.GetLogFileURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetLogFileURLResponse1> GetLogFileURLAsync(ClasseMetier.ServiceReference1.GetLogFileURL GetLogFileURL) {
            ClasseMetier.ServiceReference1.GetLogFileURLRequest inValue = new ClasseMetier.ServiceReference1.GetLogFileURLRequest();
            inValue.GetLogFileURL = GetLogFileURL;
            return ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetLogFileURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClasseMetier.ServiceReference1.GetIconURLResponse1 ClasseMetier.ServiceReference1.BasicServicePortType.GetIconURL(ClasseMetier.ServiceReference1.GetIconURLRequest request) {
            return base.Channel.GetIconURL(request);
        }
        
        public ClasseMetier.ServiceReference1.GetIconURLResponse GetIconURL(ClasseMetier.ServiceReference1.GetIconURL GetIconURL1) {
            ClasseMetier.ServiceReference1.GetIconURLRequest inValue = new ClasseMetier.ServiceReference1.GetIconURLRequest();
            inValue.GetIconURL = GetIconURL1;
            ClasseMetier.ServiceReference1.GetIconURLResponse1 retVal = ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetIconURL(inValue);
            return retVal.GetIconURLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetIconURLResponse1> ClasseMetier.ServiceReference1.BasicServicePortType.GetIconURLAsync(ClasseMetier.ServiceReference1.GetIconURLRequest request) {
            return base.Channel.GetIconURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.GetIconURLResponse1> GetIconURLAsync(ClasseMetier.ServiceReference1.GetIconURL GetIconURL) {
            ClasseMetier.ServiceReference1.GetIconURLRequest inValue = new ClasseMetier.ServiceReference1.GetIconURLRequest();
            inValue.GetIconURL = GetIconURL;
            return ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).GetIconURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClasseMetier.ServiceReference1.ChangeFriendlyNameResponse1 ClasseMetier.ServiceReference1.BasicServicePortType.ChangeFriendlyName(ClasseMetier.ServiceReference1.ChangeFriendlyNameRequest request) {
            return base.Channel.ChangeFriendlyName(request);
        }
        
        public ClasseMetier.ServiceReference1.ChangeFriendlyNameResponse ChangeFriendlyName(ClasseMetier.ServiceReference1.ChangeFriendlyName ChangeFriendlyName1) {
            ClasseMetier.ServiceReference1.ChangeFriendlyNameRequest inValue = new ClasseMetier.ServiceReference1.ChangeFriendlyNameRequest();
            inValue.ChangeFriendlyName = ChangeFriendlyName1;
            ClasseMetier.ServiceReference1.ChangeFriendlyNameResponse1 retVal = ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).ChangeFriendlyName(inValue);
            return retVal.ChangeFriendlyNameResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.ChangeFriendlyNameResponse1> ClasseMetier.ServiceReference1.BasicServicePortType.ChangeFriendlyNameAsync(ClasseMetier.ServiceReference1.ChangeFriendlyNameRequest request) {
            return base.Channel.ChangeFriendlyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClasseMetier.ServiceReference1.ChangeFriendlyNameResponse1> ChangeFriendlyNameAsync(ClasseMetier.ServiceReference1.ChangeFriendlyName ChangeFriendlyName) {
            ClasseMetier.ServiceReference1.ChangeFriendlyNameRequest inValue = new ClasseMetier.ServiceReference1.ChangeFriendlyNameRequest();
            inValue.ChangeFriendlyName = ChangeFriendlyName;
            return ((ClasseMetier.ServiceReference1.BasicServicePortType)(this)).ChangeFriendlyNameAsync(inValue);
        }
    }
}
